name: lakitu release

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Build binaries
        run: |
          apt-get update
          apt-get install gcc-mingw-w64 -y
          ./build.sh
        env:
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      - name: Generate variables
        id: lakitu
        run: |
          echo ::set-output name=VERSION::$(git describe --tags)
      - name: Upload release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: lakitu ${{ steps.lakitu.outputs.VERSION }}
          tag_name: ${{ steps.lakitu.outputs.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*.zip
